manifest:

  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v3.7-branch
      path: zephyr
      west-commands: scripts/west-commands.yml
      import:
        name-allowlist:
          - cmsis
          - hal_rpi_pico

    - name: libcsp
      url: https://github.com/libcsp/libcsp.git
      revision: develop
      path: modules/lib/libcsp

    - name: mcuboot
      url: https://github.com/zephyrproject-rtos/mcuboot
      revision: main
      path: bootloader/mcuboot

    - name: zcbor
      url: https://github.com/zephyrproject-rtos/zcbor
      revision: 75d088037eb237b18e7ec1f47c9ce494b9b95aab
      path: modules/lib/zcbor
