manifest:

  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: 30af4b26968c640d605f6e7853cff4e8daebe4f8
      path: zephyr
      west-commands: scripts/west-commands.yml
      import:
        name-allowlist:
          - cmsis
          - hal_rpi_pico

    - name: libcsp
      url: https://github.com/libcsp/libcsp.git
      revision: 1653d5b340cdf97ceb97dbf84b2dcbbfe8623e8c
      path: modules/lib/libcsp

    - name: mcuboot
      url: https://github.com/zephyrproject-rtos/mcuboot
      revision: f74b77cf7808919837c0ed14c2ead3918c546349
      path: bootloader/mcuboot

    - name: zcbor
      url: https://github.com/zephyrproject-rtos/zcbor
      revision: 75d088037eb237b18e7ec1f47c9ce494b9b95aab
      path: modules/lib/zcbor
