#!/usr/bin/env python3

import socket
import capture
import file

# Set the UDP port number
PORT = 12345

# Create a socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind(('', PORT))  # Bind without specifying an IP address

while True:
    # Receive 1 byte of data
    data, addr = sock.recvfrom(1)

    # If received 'p', return 'p'
    if data == b'p':
        sock.sendto(data, addr)

    # if received 'c', capture dng and jpg and save to each directory
    elif data == b'c':
        try:
            capture.capture_dng_jpg(file.get_name())
        except Exception as e:
            sock.sendto(b'e', addr)
            print("Capture Error")
            print(e)
        sock.sendto(b'c', addr)

    # Send 'e' for everything else
    else:
        sock.sendto(b'e', addr)

# Close the socket. Since there is a closing program, it seems
# unlikely that the ground station will be automatically closed
sock.close()
