#!/usr/bin/env python3

import socket
import capture
import file
import exifrw
import binarize

# Set the UDP port number
PORT = 12345

# Create a socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind(('', PORT))  # Bind without specifying an IP address

while True:
    # Receive 1 byte of data
    data, addr = sock.recvfrom(1)

    # If received 'p', return 'p'
    if data == b'p':
        sock.sendto(data, addr)

    # if received 'c', capture dng and jpg and save to each directory
    elif data == b'c':
        try:
            capture.capture_dng_jpg(file.get_name())
        except Exception as e:
            sock.sendto(b'e', addr)
            print("Capture Error")
            print(e)
        sock.sendto(b'c', addr)

    # if received 'm', save metadata to file
    elif data == b'm':
        try:
            exifrw.meta_save_directory()
        except Exception as e:
            sock.sendto(b'e', addr)
            print('Save metadata Error')
            print(e)
        sock.sendto(b'm', addr)

    # Send 'b' to binarized image
    elif data == b'b':
        try:
            file.loop_in_directory(binarize.binarize_xmp,'./ImageJPG')
        except Exception as e:
            sock.sendto(b'e', addr)
            print("Binarize Error")
            print(e)
        sock.sendto(b'b', addr)

    # Send 'e' for everything else
    else:
        sock.sendto(b'e', addr)

# Close the socket. Since there is a closing program, it seems
# unlikely that the ground station will be automatically closed
sock.close()
