name: Build test for Pico
on:
  push:
  pull_request:
  schedule:
    - cron: '0 10 * * 0' # Run it every Sunday 10am UTC

jobs:
  build-zephyr:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-latest
        board:
          - rpi_pico
        python-version:
          - '3.10'
          - '3.11'
        sdk-version:
          - '0.16.4'

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Python version
        run: |
          python3 --version

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: scsat1-rpi

      - name: Setup Zephyr
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: scsat1-rpi
          toolchains: arm-zephyr-eabi
          sdk-version: ${{ matrix.sdk-version }}

      - name: Build
        run: |
          west build -b ${{ matrix.board }} scsat1-rpi/pico
